export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_CITY = "SET_CURRENT_CITY";
export const SET_BOOKING_PARTNER_DETAIL = "SET_BOOKING_PARTNER_DETAIL";
